quarkus.http.port=8080

# CORS para el frontend React en desarrollo (Vite)
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173

# Usamos nuestro Neo4j de docker-compose, no el "dev services" automático
quarkus.devservices.enabled=false

# --- Neo4j (valores desde .env / variables de entorno) ---
quarkus.neo4j.uri=${NEO4J_URI:bolt://localhost:7687}
quarkus.neo4j.authentication.username=${NEO4J_USER:neo4j}
quarkus.neo4j.authentication.password=${NEO4J_PASSWORD}

# --- JWT (RSA). Las llaves se generan con scripts/generate-jwt-keys.ps1 ---
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_PATH:/publicKey.pem}
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_PATH:/privateKey.pem}
mp.jwt.verify.issuer=red-social

# Swagger UI con botón "Authorize" para pegar el token
quarkus.smallrye-openapi.security-scheme=jwt
